app/urls.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from app import views

urlpatterns = [
    # Matches any html file - to be used for gentella
    # Avoid using your .html in your resources.
    # Or create a separate django app.
    re_path(r'^.*\.html', views.pages, name='pages'),

    # The home page
    path('', views.index, name='home'),
]

cardioclassifier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('app.urls')),
    path('classifiers/', include('classifiers.urls')),
    path('samples/', include('samples.urls')),
    path('tasks/', include('tasks.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classifiers/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:classifier_id>/', views.detail, name='detail')
]

classifiers/models.py
from django.db import models

class Classifier(models.Model):
#    sample_type = models.ForeignKey(SampleType, on_delete=models.CASCADE)
    title = models.CharField(max_length=127)
    executable = models.CharField(max_length=127) # path to executable
    settings = models.CharField(max_length=1023) # command line settings
    description = models.CharField(max_length=2048) # short description

#    class Meta:
#        app_label = 'classifiers'

    def __str__(self):
        return self.title

tasks/models.py
import datetime

from django.db import models
from django.utils import timezone
from classifiers.models import Classifier

class Task(models.Model):
    uuid = models.CharField(max_length=16) # unique identifier, used to store file
    pub_date = models.DateTimeField('date published')

#    class Meta:
#        app_label = 'tasks'

    def __str__(self):
        return self.uuid

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class TaskResult(models.Model):
    task_id = models.ForeignKey(Task, on_delete=models.CASCADE)
    uuid = models.CharField(max_length=16) # unique identifier, used to store file
    classifier_id = models.ForeignKey(Classifier, on_delete=models.CASCADE)

#    class Meta:
#        app_label = 'task_results'

    def __str__(self):
        return self.uuid

classifiers/views.py
from django.shortcuts import get_object_or_404, render

from .models import Classifier

def index(request):
    latest_classifier_list = Classifier.objects.order_by('-id')[:15]
    context = {
        'latest_classifier_list': latest_classifier_list,
    }
    return render(request, 'classifiers/index.html', context)

def detail(request, classifier_id):
    classifier_ = get_object_or_404(Classifier, pk=classifier_id)
    return render(request, 'classifiers/detail.html', {'classifier': classifier_})

classifiers/templates/classifiers/detail.html
{% extends "layouts/base.html" %}

{% block title %} Classifiers {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}




<div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Classifiers</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Classifiers</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->

                    <div class="col-sm-12">
                            <h5>{{ classifier.title }}</h5>
                            <hr>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active text-uppercase" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Description</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-uppercase" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Results</a>
                                </li>
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                    <p class="mb-0">{{ classifier }}
                                    </p>
                                </div>
                                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    <ul>
                                        {% for result_ in classifier.taskresult_set.all %}
                                            <li>
                                                <a href="/media/{{ result_.uuid }}.pdf">{{  result_.uuid }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}

classifiers/templates/classifiers/index.html
{% extends "layouts/base.html" %}

{% block title %} Classifiers {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}




<div class="pcoded-content">
        <div class="pcoded-inner-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Classifiers</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="/"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Classifiers</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->


                    {% if latest_classifier_list %}
                    
                        {% for classifier_ in latest_classifier_list %}

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>{{ classifier_.title }}</h5>
                                        </div>
                                        <div class="card-block">
                                            <p> {{ classifier_.title }} </p> 
                                            <a href="/classifiers/{{ classifier_.id }}/">More details on {{ classifier_.title }}</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    {% else %}
                        <p>No classifiers are available.</p>
                    {% endif %}
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
{% endblock javascripts %}